### ISSUE TITLE
Hosted Version

### ISSUE THREAD

**Issue by SashvDave** [TrafficGuard/sophia#22]
having some trouble getting nous set up on my local machine. specifically, getting this error:
```
For help, see: https://nodejs.org/en/docs/inspector
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'ts-node/register'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at internalRequire (node:internal/modules/cjs/loader:176:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1563:5)
    at loadPreloadModules (node:internal/process/pre_execution:730:5)
    at setupUserModules (node:internal/process/pre_execution:206:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.14.0
```

Can anyone help me fix this, or is there a deployed version I can play around with?

**Comment by danielcampagnolitg** [comment]
I'll put up a public demo soon, there's some updates I need to make first before I can do that.

Has the ts-node module been installed ok? If you don't run the bin/configure script you'll need to run the commands in it.
Are you running it with `npm run start:local`? Are you able to get it running with the docker compose file?

**Comment by danielcampagnolitg** [comment]
Odd, can you delete node_modules and npm install again.

Add the project Id (not the name) for GCLOUD_PROJECT

I still need to spend some time setting up a seamless deployment setup with GitHub.  At work I have a hacked up pipeline which deploys from GitLab as thats what we use internally.

**Comment by danielcampagnolitg** [comment]
https://discord.gg/aG8DtECHcR

**Comment by danielcampagnolitg** [comment]
A close out note from our Discord discussion. The final fix was to use the `npm run start:local` script and not `node dist/index.js` to run it, as it need to be run with the ts-node plugin so it loads the import mappings via the tsconfig-paths module
